### ISSUE TITLE
Black Images

### ISSUE THREAD

**Issue by hurzl** [dfacts/staticmaplite#15]
Since yesterday the server returns black images only  ...

**Comment by DropIn** [comment]
I have the same problem. My solution, set _$tileSrcUrl_ from http:// to https:// on line 38.

`protected $tileSrcUrl = array('mapnik' => 'https://tile.openstreetmap.org/{Z}/{X}/{Y}.png',
        'osmarenderer' => 'https://otile1.mqcdn.com/tiles/1.0.0/osm/{Z}/{X}/{Y}.png',
        'cycle' => 'https://a.tile.opencyclemap.org/cycle/{Z}/{X}/{Y}.png',
    );`

**Comment by modelga** [comment]
Additionally have to change line in `tileUrlToFilename` function

```
    public function tileUrlToFilename($url)
    {
        return $this->tileCacheBaseDir . "/" . str_replace(array('http://','https://'), '', $url);
    }
```

**Comment by hurzl** [comment]
that's not working for
`http://staticmap.openstreetmap.de/staticmap.php?center=<LAT>,<LNG>...`

**Comment by Nakaner** [comment]
Note: staticmap.openstreetmap.de is gone. This issue can be closed.
