### ISSUE TITLE
Handle dateline wrapping better

### ISSUE THREAD

**Issue by harry-wood** [dfacts/staticmaplite#2]
See this image http://staticmap.openstreetmap.de/staticmap.php?center=27,-142&zoom=3&size=540x960

It should not make a black strip. Probably it should fetch tiles from the other side of the world to build the left hand side of the image in this case

**Comment by JLugagne** [comment]
Hello,

Thank you harry-wood for reporting this for me.
I've been looking at the code and found the issue. In the function createBaseMap() $startX and $startY can be negative so out of range for the api (0 <= x and y 2^(2*zoom)). cf : http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Zoom_levels
Here is a diff between my version with the fix and yours :+1: 
```
36d35
<     protected $maxtiles = 0;
186,189d184
<     public function normalizeTileCoord($position){
<       return ($position < 0) ? $this->maxtiles + $position : $position;
<     }
< 
203,204c198
<       $this->maxtiles = sqrt(pow(2,(2*$this->zoom)));
< 
---
> 
207c201
<                 $url = str_replace(array('{Z}', '{X}', '{Y}'), array($this->zoom, $this->normalizeTileCoord($x), $this->normalizeTileCoord($y)), $this->tileSrcUrl[$this->maptype]);
---
>                 $url = str_replace(array('{Z}', '{X}', '{Y}'), array($this->zoom, $x, $y), $this->tileSrcUrl[$this->maptype]);
```
Here is the result after the fix :
![map-fix](https://cloud.githubusercontent.com/assets/13189639/8584574/4eecf6ac-25d8-11e5-822e-358ab8df9e8b.png)

**Comment by flightsurvey** [comment]
Thanks for posting this as it helps me out too. Would you be interested in solving the other problem which is when the centre of the map is quite near the north or south poles?
