### ISSUE TITLE
maptype=osmarenderer should be deprecated

### ISSUE THREAD

**Issue by harry-wood** [dfacts/staticmaplite#3]
It supports maptype=osmarenderer because this tool was created years ago when we had an "osmarender" layer. That ceased to exist quite a long time ago. It's good that somebody's has "fixed" this by mapping it onto a working tile server, but...

it's a bit weird that it maps onto the mapquest open tiles, as the only way of specifying mapquest open.

Instead the tool should...
- Support maptype=mapquest as the "correct" way to specify that tile server.
- Change the http://staticmap.openstreetmap.de homepage to give that as the example and remove any mention of the old maptype=osmarender  
- Continue to the support the maptype=osmarender parameter (just start discouraging its use. It's "deprecated") 

You might also consider the same treatment for  maptype=mapnik  It should really be maptype=standard  We are discouraging people calling it the "mapnik layer" these days.

To be clear, I would advise "deprecating" certain maptype values, but please don't just _discontinue_ support for the old values though.

**Comment by harry-wood** [comment]
Another funny past mistake I only just noticed: it was never called "osmarenderer". The name was always "osmarender" for both the rendering software and the layer.

**Comment by dfacts** [comment]
contribution by pull request are welcome :)

**Comment by harry-wood** [comment]
More recently mapquest have ceased their "mapquest open" service, so my recommendation would change. No point added a maptype=mapquest parameter.  And since maptype=osmarenderer was always a mismatched name mapped onto something different, we should either drop it completely at this point (people using this will have seen broken images for the past few months anyway)  or fix this a deprecated legacy supported setting, and bring those old URLs back into working order by changing maptype=osmarenderer map onto a _working_ maptype.

**Comment by harry-wood** [comment]
@dfacts. You said that "_contributions by pull request are welcome_". I wonder, did you get chance to look at any of the contributions by pull request?
