### ISSUE TITLE
Broken by mapquest changes

### ISSUE THREAD

**Issue by harry-wood** [dfacts/staticmaplite#8]
Mapquest recently started requiring API keys for all tile requests.

This has broken the website http://staticmap.openstreetmap.de (it now takes a very long time to load a broken image). Likewise any static map image URLs using `maptype=osmarenderer` are now broken. 

Actually it's hopelessly slow for any maptype URL, I guess because the server is dying with a queue of requests to mapquest clogging things up.

Simplest solution might be for you to register an mapquest developer account for StaticMapLite

**Comment by harry-wood** [comment]
hmm maybe I'm wrong about the cause of that actually. it might be nothing to do with mapquest. Not sure if they've made that change yet (but they will!).   ....in which case the service is dead for some other reason

**Comment by nomoregrapes** [comment]
Earlier today I made some images with the mapquest layer & this staticmap class. Fine, although not sure about timings to create the images.

Although checking now, the static map example site was slow and http://www.downforeveryoneorjustme.com/http://staticmap.openstreetmap.de/ even said it was down.

**Comment by nomoregrapes** [comment]
Seemingly, images can be created without warning. Due to Mapquest no longer allowing direct access. E.g.
![small_map_image](https://cloud.githubusercontent.com/assets/1181194/16762468/89495662-481c-11e6-8502-063ed76b4348.png)

**Comment by nxtpl** [comment]
In my case it was sufficient to switch to different tileSrcUrl, by switching maptype=osmarenderer to to maptype=mapnik

**Comment by harry-wood** [comment]
Yes. Users will need to switch to one of the other maptype settings. That's the solution from a user point of view.

I was originally reporting a slow-down, but that seems to be caused by something else, not the mapquest change, so this discussion has become confused. Sorry about that. Closing it
